[package]
name = "ferris-loader"
version = "0.1.0"
edition = "2021"

[dependencies]
ferris-dom = { path = "../ferris-dom" }
ferris-css = { path = "../ferris-css" }
ferris-style = { path = "../ferris-style" }
ferris-scene = { path = "../ferris-scene" }
ureq = "2"
url = "2"
image = { version = "0.25", default-features = false, features = ["png", "jpeg"] }
base64 = "0.22"
