[package]
name = "ferris-paint"
version = "0.1.0"
edition = "2021"

[dependencies]
ferris-layout = { path = "../ferris-layout" }
ferris-compositor = { path = "../ferris-compositor" }
ferris-dom = { path = "../ferris-dom" }
ferris-style = { path = "../ferris-style" }

[dev-dependencies]
ferris-css = { path = "../ferris-css" }
